--
-- PostgreSQL database dump
--

\restrict 0rucZ3lv0sP0vTQkba396UBedZbRsIdLXX4dML6cWDUNyvuXh2H7Gk6iRZLC0Q2

-- Dumped from database version 17.7 (bdc8956)
-- Dumped by pg_dump version 18.0

-- Started on 2025-12-21 09:02:58 AST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3507 (class 1262 OID 16391)
-- Name: neondb; Type: DATABASE; Schema: -; Owner: neondb_owner
--

CREATE DATABASE neondb WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = builtin LOCALE = 'C.UTF-8' BUILTIN_LOCALE = 'C.UTF-8';


ALTER DATABASE neondb OWNER TO neondb_owner;

\unrestrict 0rucZ3lv0sP0vTQkba396UBedZbRsIdLXX4dML6cWDUNyvuXh2H7Gk6iRZLC0Q2
\connect neondb
\restrict 0rucZ3lv0sP0vTQkba396UBedZbRsIdLXX4dML6cWDUNyvuXh2H7Gk6iRZLC0Q2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3509 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 229 (class 1259 OID 41002)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO neondb_owner;

--
-- TOC entry 228 (class 1259 OID 41001)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 40966)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetRoles" (
    "Id" integer NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO neondb_owner;

--
-- TOC entry 218 (class 1259 OID 40965)
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."AspNetRoles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 41015)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO neondb_owner;

--
-- TOC entry 230 (class 1259 OID 41014)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 41027)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO neondb_owner;

--
-- TOC entry 233 (class 1259 OID 41039)
-- Name: AspNetUserPasskeys; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetUserPasskeys" (
    "CredentialId" bytea NOT NULL,
    "UserId" integer NOT NULL,
    "Data" jsonb NOT NULL
);


ALTER TABLE public."AspNetUserPasskeys" OWNER TO neondb_owner;

--
-- TOC entry 234 (class 1259 OID 41051)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO neondb_owner;

--
-- TOC entry 235 (class 1259 OID 41066)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO neondb_owner;

--
-- TOC entry 221 (class 1259 OID 40974)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."AspNetUsers" (
    "Id" integer NOT NULL,
    "Nombres" character varying(50) NOT NULL,
    "Apellidos" character varying(50) NOT NULL,
    "Direccion" character varying(150) NOT NULL,
    "Email" character varying(256) NOT NULL,
    "PhoneNumber" character varying(256) NOT NULL,
    "UserName" character varying(256) NOT NULL,
    "NormalizedUserName" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO neondb_owner;

--
-- TOC entry 220 (class 1259 OID 40973)
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."AspNetUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 40982)
-- Name: ConfiguracionesSistema; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."ConfiguracionesSistema" (
    "ConfiguracionSistemaId" integer NOT NULL,
    "RequiereArchivoConHash" boolean NOT NULL,
    "ReciboPagoObligatorio" boolean NOT NULL,
    "DocumentosFavoritosRaw" text NOT NULL,
    "UltimaActualizacion" timestamp with time zone NOT NULL
);


ALTER TABLE public."ConfiguracionesSistema" OWNER TO neondb_owner;

--
-- TOC entry 222 (class 1259 OID 40981)
-- Name: ConfiguracionesSistema_ConfiguracionSistemaId_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."ConfiguracionesSistema" ALTER COLUMN "ConfiguracionSistemaId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ConfiguracionesSistema_ConfiguracionSistemaId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 41097)
-- Name: Documentos; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."Documentos" (
    "DocumentoId" integer NOT NULL,
    "SolicitudDocumentoId" integer NOT NULL,
    "SubidoPorUsuarioId" integer NOT NULL,
    "NombreOriginal" text NOT NULL,
    "RutaR2" text NOT NULL,
    "HashSha256" text NOT NULL,
    "TokenAcceso" text NOT NULL,
    "FechaSubida" timestamp with time zone NOT NULL,
    "TamanoBytes" bigint NOT NULL,
    "ContentType" text NOT NULL,
    "Activo" boolean NOT NULL
);


ALTER TABLE public."Documentos" OWNER TO neondb_owner;

--
-- TOC entry 238 (class 1259 OID 41096)
-- Name: Documentos_DocumentoId_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."Documentos" ALTER COLUMN "DocumentoId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Documentos_DocumentoId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 40990)
-- Name: Estudiantes; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."Estudiantes" (
    "EstudianteId" integer NOT NULL,
    "Nombres" character varying(50) NOT NULL,
    "Apellidos" character varying(50) NOT NULL,
    "Matricula" character varying(9) NOT NULL,
    "Carrera" character varying(100) NOT NULL,
    "Telefono" character varying(12) NOT NULL,
    "Correo" character varying(100) NOT NULL,
    "Direccion" character varying(150) NOT NULL,
    "EsEgresado" boolean NOT NULL,
    "Activo" boolean NOT NULL
);


ALTER TABLE public."Estudiantes" OWNER TO neondb_owner;

--
-- TOC entry 224 (class 1259 OID 40989)
-- Name: Estudiantes_EstudianteId_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."Estudiantes" ALTER COLUMN "EstudianteId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Estudiantes_EstudianteId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 41079)
-- Name: SolicitudesDocumentos; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."SolicitudesDocumentos" (
    "SolicitudDocumentoId" integer NOT NULL,
    "TipoDocumentoId" integer NOT NULL,
    "EstudianteId" integer NOT NULL,
    "EstadoProceso" text NOT NULL,
    "DescripcionAdicional" text,
    "FechaSolicitud" timestamp with time zone NOT NULL,
    "FechaFinalizado" timestamp with time zone,
    "FechaEntrega" timestamp with time zone,
    "Activo" boolean NOT NULL
);


ALTER TABLE public."SolicitudesDocumentos" OWNER TO neondb_owner;

--
-- TOC entry 241 (class 1259 OID 41115)
-- Name: SolicitudesDocumentosRegistradores; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."SolicitudesDocumentosRegistradores" (
    "SolicitudDocumentoRegistradorId" integer NOT NULL,
    "SolicitudDocumentoId" integer NOT NULL,
    "RegistradorId" integer NOT NULL,
    "FechaTrabajo" timestamp with time zone NOT NULL,
    "DescripcionTrabajo" character varying(300)
);


ALTER TABLE public."SolicitudesDocumentosRegistradores" OWNER TO neondb_owner;

--
-- TOC entry 240 (class 1259 OID 41114)
-- Name: SolicitudesDocumentosRegistra_SolicitudDocumentoRegistrador_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."SolicitudesDocumentosRegistradores" ALTER COLUMN "SolicitudDocumentoRegistradorId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SolicitudesDocumentosRegistra_SolicitudDocumentoRegistrador_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 41078)
-- Name: SolicitudesDocumentos_SolicitudDocumentoId_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."SolicitudesDocumentos" ALTER COLUMN "SolicitudDocumentoId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SolicitudesDocumentos_SolicitudDocumentoId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 40996)
-- Name: TiposDocumentos; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."TiposDocumentos" (
    "TipoDocumentoId" integer NOT NULL,
    "Nombre" character varying(100) NOT NULL
);


ALTER TABLE public."TiposDocumentos" OWNER TO neondb_owner;

--
-- TOC entry 226 (class 1259 OID 40995)
-- Name: TiposDocumentos_TipoDocumentoId_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public."TiposDocumentos" ALTER COLUMN "TipoDocumentoId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TiposDocumentos_TipoDocumentoId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 40960)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO neondb_owner;

--
-- TOC entry 3489 (class 0 OID 41002)
-- Dependencies: 229
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--



--
-- TOC entry 3479 (class 0 OID 40966)
-- Dependencies: 219
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."AspNetRoles" VALUES (1, 'Administrador', 'ADMINISTRADOR', 'admin-stamp');
INSERT INTO public."AspNetRoles" VALUES (2, 'Registrador', 'REGISTRADOR', 'registrador-stamp');


--
-- TOC entry 3491 (class 0 OID 41015)
-- Dependencies: 231
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--



--
-- TOC entry 3492 (class 0 OID 41027)
-- Dependencies: 232
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--



--
-- TOC entry 3493 (class 0 OID 41039)
-- Dependencies: 233
-- Data for Name: AspNetUserPasskeys; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--



--
-- TOC entry 3494 (class 0 OID 41051)
-- Dependencies: 234
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."AspNetUserRoles" VALUES (1, 1);


--
-- TOC entry 3495 (class 0 OID 41066)
-- Dependencies: 235
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--



--
-- TOC entry 3481 (class 0 OID 40974)
-- Dependencies: 221
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."AspNetUsers" VALUES (1, 'Administrador', 'Del Sistema', 'San Francisco de Macorís', 'admin@ucne.edu.do', '', 'admin', 'ADMIN', 'ADMIN@UCNE.EDU.DO', false, 'AQAAAAIAAYagAAAAEMnRieJLtO0k/Mv75oJw3AWMP/CFhqba42LJNnLiGlLXCmqmXFJ+MM9flIMz4PXa9g==', 'admin-security-stamp', 'admin-concurrency-stamp', false, false, NULL, false, 0);


--
-- TOC entry 3483 (class 0 OID 40982)
-- Dependencies: 223
-- Data for Name: ConfiguracionesSistema; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."ConfiguracionesSistema" VALUES (1, true, true, '', '2025-12-21 01:04:10.678289+00');


--
-- TOC entry 3499 (class 0 OID 41097)
-- Dependencies: 239
-- Data for Name: Documentos; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."Documentos" VALUES (1, 1, 1, 'pdf-sample_0.pdf', '2025_12_21/doc_fa3b25df0339407a8990b505cc8a0367_pdf-sample_0.pdf', '3df79d34abbca99308e79cb94461c1893582604d68329a41fd4bec1885e6adb4', 'b0a555bf962946488b8b8ec53acdf44d', '2025-12-21 12:44:17.582405+00', 13264, 'application/pdf', true);


--
-- TOC entry 3485 (class 0 OID 40990)
-- Dependencies: 225
-- Data for Name: Estudiantes; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."Estudiantes" VALUES (1, 'Juan', 'Pérez Gómez', '2025-0001', 'Ingeniería en Software', '809-555-1234', 'jperez@ucne.edu.do', 'Calle Duarte #12', false, true);
INSERT INTO public."Estudiantes" VALUES (2, 'Ana', 'Gómez Castillo', '2025-0002', 'Contabilidad', '829-444-5678', 'agomez@ucne.edu.do', 'Calle Sánchez #45', true, true);


--
-- TOC entry 3497 (class 0 OID 41079)
-- Dependencies: 237
-- Data for Name: SolicitudesDocumentos; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."SolicitudesDocumentos" VALUES (1, 1, 2, 'Finalizado', NULL, '2025-12-21 12:42:52.983504+00', '2025-12-21 00:00:00+00', '2025-12-21 00:00:00+00', true);


--
-- TOC entry 3501 (class 0 OID 41115)
-- Dependencies: 241
-- Data for Name: SolicitudesDocumentosRegistradores; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."SolicitudesDocumentosRegistradores" VALUES (1, 1, 1, '2025-12-21 12:43:01.0634+00', 'Solicitud creada');
INSERT INTO public."SolicitudesDocumentosRegistradores" VALUES (2, 1, 1, '2025-12-21 12:43:15.003407+00', 'Se cambió el estado a En Proceso');
INSERT INTO public."SolicitudesDocumentosRegistradores" VALUES (3, 1, 1, '2025-12-21 12:44:17.582616+00', 'Subio PDF y s finalizo');


--
-- TOC entry 3487 (class 0 OID 40996)
-- Dependencies: 227
-- Data for Name: TiposDocumentos; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."TiposDocumentos" VALUES (1, 'Certificación de Estudiante');
INSERT INTO public."TiposDocumentos" VALUES (2, 'Certificación con Requerimientos por Casos Especifícos');
INSERT INTO public."TiposDocumentos" VALUES (3, 'Certificación de Grado');
INSERT INTO public."TiposDocumentos" VALUES (4, 'Certificación de Última Materia');
INSERT INTO public."TiposDocumentos" VALUES (5, 'Certificación de Internado Rotatorio');
INSERT INTO public."TiposDocumentos" VALUES (6, 'Certificación de Convenio');
INSERT INTO public."TiposDocumentos" VALUES (7, 'Certificación de Monográfico');
INSERT INTO public."TiposDocumentos" VALUES (8, 'Certificación de Anillo');
INSERT INTO public."TiposDocumentos" VALUES (9, 'Revisión de Expediente y Récord de Notas Regular');
INSERT INTO public."TiposDocumentos" VALUES (10, 'Récord de Notas Egresado');
INSERT INTO public."TiposDocumentos" VALUES (11, 'Récord de Notas Manuales de Matrículas Antiguas');
INSERT INTO public."TiposDocumentos" VALUES (12, 'Documentos Académicos para Legalización del MESCyT');
INSERT INTO public."TiposDocumentos" VALUES (13, 'Documentos Académicos con Homologaciones para Legalización del MESCyT');
INSERT INTO public."TiposDocumentos" VALUES (14, 'Documentos para Validación de Estudios en Colombia');
INSERT INTO public."TiposDocumentos" VALUES (15, 'Otro (Especificar)');


--
-- TOC entry 3477 (class 0 OID 40960)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: neondb_owner
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20251221004001_Inicial', '10.0.1');


--
-- TOC entry 3510 (class 0 OID 0)
-- Dependencies: 228
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 3511 (class 0 OID 0)
-- Dependencies: 218
-- Name: AspNetRoles_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."AspNetRoles_Id_seq"', 3, false);


--
-- TOC entry 3512 (class 0 OID 0)
-- Dependencies: 230
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3513 (class 0 OID 0)
-- Dependencies: 220
-- Name: AspNetUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."AspNetUsers_Id_seq"', 2, false);


--
-- TOC entry 3514 (class 0 OID 0)
-- Dependencies: 222
-- Name: ConfiguracionesSistema_ConfiguracionSistemaId_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."ConfiguracionesSistema_ConfiguracionSistemaId_seq"', 1, false);


--
-- TOC entry 3515 (class 0 OID 0)
-- Dependencies: 238
-- Name: Documentos_DocumentoId_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."Documentos_DocumentoId_seq"', 1, true);


--
-- TOC entry 3516 (class 0 OID 0)
-- Dependencies: 224
-- Name: Estudiantes_EstudianteId_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."Estudiantes_EstudianteId_seq"', 2, true);


--
-- TOC entry 3517 (class 0 OID 0)
-- Dependencies: 240
-- Name: SolicitudesDocumentosRegistra_SolicitudDocumentoRegistrador_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."SolicitudesDocumentosRegistra_SolicitudDocumentoRegistrador_seq"', 3, true);


--
-- TOC entry 3518 (class 0 OID 0)
-- Dependencies: 236
-- Name: SolicitudesDocumentos_SolicitudDocumentoId_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."SolicitudesDocumentos_SolicitudDocumentoId_seq"', 1, true);


--
-- TOC entry 3519 (class 0 OID 0)
-- Dependencies: 226
-- Name: TiposDocumentos_TipoDocumentoId_seq; Type: SEQUENCE SET; Schema: public; Owner: neondb_owner
--

SELECT pg_catalog.setval('public."TiposDocumentos_TipoDocumentoId_seq"', 16, false);


--
-- TOC entry 3292 (class 2606 OID 41008)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3278 (class 2606 OID 40972)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3295 (class 2606 OID 41021)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3298 (class 2606 OID 41033)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3301 (class 2606 OID 41045)
-- Name: AspNetUserPasskeys PK_AspNetUserPasskeys; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserPasskeys"
    ADD CONSTRAINT "PK_AspNetUserPasskeys" PRIMARY KEY ("CredentialId");


--
-- TOC entry 3304 (class 2606 OID 41055)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3306 (class 2606 OID 41072)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3282 (class 2606 OID 40980)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3285 (class 2606 OID 40988)
-- Name: ConfiguracionesSistema PK_ConfiguracionesSistema; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."ConfiguracionesSistema"
    ADD CONSTRAINT "PK_ConfiguracionesSistema" PRIMARY KEY ("ConfiguracionSistemaId");


--
-- TOC entry 3314 (class 2606 OID 41103)
-- Name: Documentos PK_Documentos; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."Documentos"
    ADD CONSTRAINT "PK_Documentos" PRIMARY KEY ("DocumentoId");


--
-- TOC entry 3287 (class 2606 OID 40994)
-- Name: Estudiantes PK_Estudiantes; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."Estudiantes"
    ADD CONSTRAINT "PK_Estudiantes" PRIMARY KEY ("EstudianteId");


--
-- TOC entry 3310 (class 2606 OID 41085)
-- Name: SolicitudesDocumentos PK_SolicitudesDocumentos; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."SolicitudesDocumentos"
    ADD CONSTRAINT "PK_SolicitudesDocumentos" PRIMARY KEY ("SolicitudDocumentoId");


--
-- TOC entry 3318 (class 2606 OID 41119)
-- Name: SolicitudesDocumentosRegistradores PK_SolicitudesDocumentosRegistradores; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."SolicitudesDocumentosRegistradores"
    ADD CONSTRAINT "PK_SolicitudesDocumentosRegistradores" PRIMARY KEY ("SolicitudDocumentoRegistradorId");


--
-- TOC entry 3289 (class 2606 OID 41000)
-- Name: TiposDocumentos PK_TiposDocumentos; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."TiposDocumentos"
    ADD CONSTRAINT "PK_TiposDocumentos" PRIMARY KEY ("TipoDocumentoId");


--
-- TOC entry 3276 (class 2606 OID 40964)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3280 (class 1259 OID 41136)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3290 (class 1259 OID 41130)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3293 (class 1259 OID 41132)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3296 (class 1259 OID 41133)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3299 (class 1259 OID 41134)
-- Name: IX_AspNetUserPasskeys_UserId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_AspNetUserPasskeys_UserId" ON public."AspNetUserPasskeys" USING btree ("UserId");


--
-- TOC entry 3302 (class 1259 OID 41135)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3311 (class 1259 OID 41138)
-- Name: IX_Documentos_SolicitudDocumentoId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX "IX_Documentos_SolicitudDocumentoId" ON public."Documentos" USING btree ("SolicitudDocumentoId");


--
-- TOC entry 3312 (class 1259 OID 41139)
-- Name: IX_Documentos_SubidoPorUsuarioId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_Documentos_SubidoPorUsuarioId" ON public."Documentos" USING btree ("SubidoPorUsuarioId");


--
-- TOC entry 3315 (class 1259 OID 41142)
-- Name: IX_SolicitudesDocumentosRegistradores_RegistradorId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_SolicitudesDocumentosRegistradores_RegistradorId" ON public."SolicitudesDocumentosRegistradores" USING btree ("RegistradorId");


--
-- TOC entry 3316 (class 1259 OID 41143)
-- Name: IX_SolicitudesDocumentosRegistradores_SolicitudDocumentoId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_SolicitudesDocumentosRegistradores_SolicitudDocumentoId" ON public."SolicitudesDocumentosRegistradores" USING btree ("SolicitudDocumentoId");


--
-- TOC entry 3307 (class 1259 OID 41140)
-- Name: IX_SolicitudesDocumentos_EstudianteId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_SolicitudesDocumentos_EstudianteId" ON public."SolicitudesDocumentos" USING btree ("EstudianteId");


--
-- TOC entry 3308 (class 1259 OID 41141)
-- Name: IX_SolicitudesDocumentos_TipoDocumentoId; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX "IX_SolicitudesDocumentos_TipoDocumentoId" ON public."SolicitudesDocumentos" USING btree ("TipoDocumentoId");


--
-- TOC entry 3279 (class 1259 OID 41131)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3283 (class 1259 OID 41137)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3319 (class 2606 OID 41009)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3320 (class 2606 OID 41022)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3321 (class 2606 OID 41034)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3322 (class 2606 OID 41046)
-- Name: AspNetUserPasskeys FK_AspNetUserPasskeys_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserPasskeys"
    ADD CONSTRAINT "FK_AspNetUserPasskeys_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3323 (class 2606 OID 41056)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3324 (class 2606 OID 41061)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3325 (class 2606 OID 41073)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3328 (class 2606 OID 41104)
-- Name: Documentos FK_Documentos_AspNetUsers_SubidoPorUsuarioId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."Documentos"
    ADD CONSTRAINT "FK_Documentos_AspNetUsers_SubidoPorUsuarioId" FOREIGN KEY ("SubidoPorUsuarioId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3329 (class 2606 OID 41109)
-- Name: Documentos FK_Documentos_SolicitudesDocumentos_SolicitudDocumentoId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."Documentos"
    ADD CONSTRAINT "FK_Documentos_SolicitudesDocumentos_SolicitudDocumentoId" FOREIGN KEY ("SolicitudDocumentoId") REFERENCES public."SolicitudesDocumentos"("SolicitudDocumentoId") ON DELETE CASCADE;


--
-- TOC entry 3330 (class 2606 OID 41120)
-- Name: SolicitudesDocumentosRegistradores FK_SolicitudesDocumentosRegistradores_AspNetUsers_RegistradorId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."SolicitudesDocumentosRegistradores"
    ADD CONSTRAINT "FK_SolicitudesDocumentosRegistradores_AspNetUsers_RegistradorId" FOREIGN KEY ("RegistradorId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3331 (class 2606 OID 41125)
-- Name: SolicitudesDocumentosRegistradores FK_SolicitudesDocumentosRegistradores_SolicitudesDocumentos_So~; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."SolicitudesDocumentosRegistradores"
    ADD CONSTRAINT "FK_SolicitudesDocumentosRegistradores_SolicitudesDocumentos_So~" FOREIGN KEY ("SolicitudDocumentoId") REFERENCES public."SolicitudesDocumentos"("SolicitudDocumentoId") ON DELETE CASCADE;


--
-- TOC entry 3326 (class 2606 OID 41086)
-- Name: SolicitudesDocumentos FK_SolicitudesDocumentos_Estudiantes_EstudianteId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."SolicitudesDocumentos"
    ADD CONSTRAINT "FK_SolicitudesDocumentos_Estudiantes_EstudianteId" FOREIGN KEY ("EstudianteId") REFERENCES public."Estudiantes"("EstudianteId") ON DELETE CASCADE;


--
-- TOC entry 3327 (class 2606 OID 41091)
-- Name: SolicitudesDocumentos FK_SolicitudesDocumentos_TiposDocumentos_TipoDocumentoId; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public."SolicitudesDocumentos"
    ADD CONSTRAINT "FK_SolicitudesDocumentos_TiposDocumentos_TipoDocumentoId" FOREIGN KEY ("TipoDocumentoId") REFERENCES public."TiposDocumentos"("TipoDocumentoId") ON DELETE CASCADE;


--
-- TOC entry 3508 (class 0 OID 0)
-- Dependencies: 3507
-- Name: DATABASE neondb; Type: ACL; Schema: -; Owner: neondb_owner
--

GRANT ALL ON DATABASE neondb TO neon_superuser;


--
-- TOC entry 2110 (class 826 OID 16394)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO neon_superuser WITH GRANT OPTION;


--
-- TOC entry 2109 (class 826 OID 16393)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: cloud_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT ALL ON TABLES TO neon_superuser WITH GRANT OPTION;


-- Completed on 2025-12-21 09:03:07 AST

--
-- PostgreSQL database dump complete
--

\unrestrict 0rucZ3lv0sP0vTQkba396UBedZbRsIdLXX4dML6cWDUNyvuXh2H7Gk6iRZLC0Q2

