// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegistroUCNE.DAL;

#nullable disable

namespace RegistroUCNE.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegistroUCNE.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("ConfiguracionSistemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfiguracionSistemaId"));

                    b.Property<bool>("RequiereArchivoConHash")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConfiguracionSistemaId");

                    b.ToTable("ConfiguracionesSistema");
                });

            modelBuilder.Entity("RegistroUCNE.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ArchivoPdfRuta")
                        .HasColumnType("text");

                    b.Property<string>("DescripcionAdicional")
                        .HasColumnType("text");

                    b.Property<string>("EstadoProceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinalizado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashArchivo")
                        .HasColumnType("text");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("integer");

                    b.HasKey("DocumentoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("RegistroUCNE.Models.DocumentoRegistrador", b =>
                {
                    b.Property<int>("DocumentoRegistradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentoRegistradorId"));

                    b.Property<string>("DescripcionTrabajo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaTrabajo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistradorId")
                        .HasColumnType("integer");

                    b.HasKey("DocumentoRegistradorId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("RegistradorId");

                    b.ToTable("DocumentoRegistradores");
                });

            modelBuilder.Entity("RegistroUCNE.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstudianteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EsEgresado")
                        .HasColumnType("boolean");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("RegistroUCNE.Models.Registrador", b =>
                {
                    b.Property<int>("RegistradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistradorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RegistradorId");

                    b.ToTable("Registradores");

                    b.HasData(
                        new
                        {
                            RegistradorId = 1,
                            Activo = true,
                            Apellidos = "Del Sistema",
                            Contrasena = "$2a$11$WgzaECgDTNz.bkhft1.0ju8CiPq6uD1ILAznXmsm19DgHW6REa0Rq",
                            Correo = "admin@ucne.edu.do",
                            Direccion = "San Francisco de Macorís",
                            NombreUsuario = "admin",
                            Nombres = "Administrador"
                        });
                });

            modelBuilder.Entity("RegistroUCNE.Models.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoDocumentoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TipoDocumentos");

                    b.HasData(
                        new
                        {
                            TipoDocumentoId = 1,
                            Nombre = "Certificación de Estudiante"
                        },
                        new
                        {
                            TipoDocumentoId = 2,
                            Nombre = "Certificación con Requerimientos por Casos Especifícos"
                        },
                        new
                        {
                            TipoDocumentoId = 3,
                            Nombre = "Certificación de Grado"
                        },
                        new
                        {
                            TipoDocumentoId = 4,
                            Nombre = "Certificación de Última Materia"
                        },
                        new
                        {
                            TipoDocumentoId = 5,
                            Nombre = "Certificación de Internado Rotatorio"
                        },
                        new
                        {
                            TipoDocumentoId = 6,
                            Nombre = "Certificación de Convenio"
                        },
                        new
                        {
                            TipoDocumentoId = 7,
                            Nombre = "Certificación de Monográfico"
                        },
                        new
                        {
                            TipoDocumentoId = 8,
                            Nombre = "Certificación de Anillo"
                        },
                        new
                        {
                            TipoDocumentoId = 9,
                            Nombre = "Revisión de Expediente y Récord de Notas Regular"
                        },
                        new
                        {
                            TipoDocumentoId = 10,
                            Nombre = "Récord de Notas Egresado"
                        },
                        new
                        {
                            TipoDocumentoId = 11,
                            Nombre = "Récord de Notas Manuales de Matrículas Antiguas"
                        },
                        new
                        {
                            TipoDocumentoId = 12,
                            Nombre = "Documentos Académicos para Legalización del MESCyT"
                        },
                        new
                        {
                            TipoDocumentoId = 13,
                            Nombre = "Documentos Académicos con Homologaciones para Legalización del MESCyT"
                        },
                        new
                        {
                            TipoDocumentoId = 14,
                            Nombre = "Documentos para Validación de Estudios en Colombia"
                        },
                        new
                        {
                            TipoDocumentoId = 15,
                            Nombre = "Otro (Especificar)"
                        });
                });

            modelBuilder.Entity("RegistroUCNE.Models.Documento", b =>
                {
                    b.HasOne("RegistroUCNE.Models.Estudiante", "Estudiante")
                        .WithMany("Documentos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroUCNE.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("RegistroUCNE.Models.DocumentoRegistrador", b =>
                {
                    b.HasOne("RegistroUCNE.Models.Documento", "Documento")
                        .WithMany("DocumentoRegistradores")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroUCNE.Models.Registrador", "Registrador")
                        .WithMany("DocumentoRegistradores")
                        .HasForeignKey("RegistradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Registrador");
                });

            modelBuilder.Entity("RegistroUCNE.Models.Documento", b =>
                {
                    b.Navigation("DocumentoRegistradores");
                });

            modelBuilder.Entity("RegistroUCNE.Models.Estudiante", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("RegistroUCNE.Models.Registrador", b =>
                {
                    b.Navigation("DocumentoRegistradores");
                });

            modelBuilder.Entity("RegistroUCNE.Models.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
